elasticsearch:
  image: elasticsearch:latest
  command: elasticsearch -Des.network.host=0.0.0.0
  ports:
    - "9200:9200"
    - "9300:9300"
redis:
  image: redis
  ports:
    - "6379:6379"
logstash:
  image: logstash:latest
  command: logstash -f /etc/logstash/conf.d/logstash.conf
  volumes:
    - ./logstash/config:/etc/logstash/conf.d
  ports:
    - "5000:5000"
  links:
    - elasticsearch
    - redis
  environment:
    - LS_HEAP_SIZE=1024m
kibana:
  build: kibana/
  volumes:
    - ./kibana/config:/opt/kibana/config
  ports:
    - "5601:5601"
  links:
    - elasticsearch

